I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/semaslava.rpy", line 49, in script
    
ScriptError: could not find label 'fail'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/semaslava.rpy", line 49, in script
    
  File "E:\Games\renpy\renpy-6.99.12.3-sdk\renpy\ast.py", line 1527, in execute
    rv = renpy.game.script.lookup(target)
  File "E:\Games\renpy\renpy-6.99.12.3-sdk\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'fail'.

Windows-8-6.2.9200
Ren'Py 6.99.12.3.2123
The last March 1.0
